repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/ansible/ansible-lint
    rev: v6.0.0
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$

-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
    -   id: yamllint
        args: [--strict] 